package com.umbrella.protobuf.demo2;// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: StudentSampe.proto

public final class StudentSample {
  private StudentSample() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface StudentOrBuilder extends
      // @@protoc_insertion_point(interface_extends:Student)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional int32 sid = 1;</code>
     */
    boolean hasSid();
    /**
     * <code>optional int32 sid = 1;</code>
     */
    int getSid();

    /**
     * <code>optional bytes sname = 2;</code>
     */
    boolean hasSname();
    /**
     * <code>optional bytes sname = 2;</code>
     */
    com.google.protobuf.ByteString getSname();

    /**
     * <code>optional .Teacher teacher = 3;</code>
     */
    boolean hasTeacher();
    /**
     * <code>optional .Teacher teacher = 3;</code>
     */
    Teacher getTeacher();
    /**
     * <code>optional .Teacher teacher = 3;</code>
     */
    TeacherOrBuilder getTeacherOrBuilder();

    /**
     * <code>repeated string hobbies = 4;</code>
     */
    com.google.protobuf.ProtocolStringList
        getHobbiesList();
    /**
     * <code>repeated string hobbies = 4;</code>
     */
    int getHobbiesCount();
    /**
     * <code>repeated string hobbies = 4;</code>
     */
    String getHobbies(int index);
    /**
     * <code>repeated string hobbies = 4;</code>
     */
    com.google.protobuf.ByteString
        getHobbiesBytes(int index);

    /**
     * <code>repeated bytes courses = 5;</code>
     */
    java.util.List<com.google.protobuf.ByteString> getCoursesList();
    /**
     * <code>repeated bytes courses = 5;</code>
     */
    int getCoursesCount();
    /**
     * <code>repeated bytes courses = 5;</code>
     */
    com.google.protobuf.ByteString getCourses(int index);
  }
  /**
   * Protobuf type {@code Student}
   */
  public static final class Student extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:Student)
      StudentOrBuilder {
    // Use Student.newBuilder() to construct.
    private Student(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private Student(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final Student defaultInstance;
    public static Student getDefaultInstance() {
      return defaultInstance;
    }

    public Student getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private Student(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              sid_ = input.readInt32();
              break;
            }
            case 18: {
              bitField0_ |= 0x00000002;
              sname_ = input.readBytes();
              break;
            }
            case 26: {
              Teacher.Builder subBuilder = null;
              if (((bitField0_ & 0x00000004) == 0x00000004)) {
                subBuilder = teacher_.toBuilder();
              }
              teacher_ = input.readMessage(Teacher.PARSER, extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(teacher_);
                teacher_ = subBuilder.buildPartial();
              }
              bitField0_ |= 0x00000004;
              break;
            }
            case 34: {
              com.google.protobuf.ByteString bs = input.readBytes();
              if (!((mutable_bitField0_ & 0x00000008) == 0x00000008)) {
                hobbies_ = new com.google.protobuf.LazyStringArrayList();
                mutable_bitField0_ |= 0x00000008;
              }
              hobbies_.add(bs);
              break;
            }
            case 42: {
              if (!((mutable_bitField0_ & 0x00000010) == 0x00000010)) {
                courses_ = new java.util.ArrayList<com.google.protobuf.ByteString>();
                mutable_bitField0_ |= 0x00000010;
              }
              courses_.add(input.readBytes());
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000008) == 0x00000008)) {
          hobbies_ = hobbies_.getUnmodifiableView();
        }
        if (((mutable_bitField0_ & 0x00000010) == 0x00000010)) {
          courses_ = java.util.Collections.unmodifiableList(courses_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return StudentSample.internal_static_Student_descriptor;
    }

    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return StudentSample.internal_static_Student_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              Student.class, Builder.class);
    }

    public static com.google.protobuf.Parser<Student> PARSER =
        new com.google.protobuf.AbstractParser<Student>() {
      public Student parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Student(input, extensionRegistry);
      }
    };

    @Override
    public com.google.protobuf.Parser<Student> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    public static final int SID_FIELD_NUMBER = 1;
    private int sid_;
    /**
     * <code>optional int32 sid = 1;</code>
     */
    public boolean hasSid() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>optional int32 sid = 1;</code>
     */
    public int getSid() {
      return sid_;
    }

    public static final int SNAME_FIELD_NUMBER = 2;
    private com.google.protobuf.ByteString sname_;
    /**
     * <code>optional bytes sname = 2;</code>
     */
    public boolean hasSname() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>optional bytes sname = 2;</code>
     */
    public com.google.protobuf.ByteString getSname() {
      return sname_;
    }

    public static final int TEACHER_FIELD_NUMBER = 3;
    private Teacher teacher_;
    /**
     * <code>optional .Teacher teacher = 3;</code>
     */
    public boolean hasTeacher() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>optional .Teacher teacher = 3;</code>
     */
    public Teacher getTeacher() {
      return teacher_;
    }
    /**
     * <code>optional .Teacher teacher = 3;</code>
     */
    public TeacherOrBuilder getTeacherOrBuilder() {
      return teacher_;
    }

    public static final int HOBBIES_FIELD_NUMBER = 4;
    private com.google.protobuf.LazyStringList hobbies_;
    /**
     * <code>repeated string hobbies = 4;</code>
     */
    public com.google.protobuf.ProtocolStringList
        getHobbiesList() {
      return hobbies_;
    }
    /**
     * <code>repeated string hobbies = 4;</code>
     */
    public int getHobbiesCount() {
      return hobbies_.size();
    }
    /**
     * <code>repeated string hobbies = 4;</code>
     */
    public String getHobbies(int index) {
      return hobbies_.get(index);
    }
    /**
     * <code>repeated string hobbies = 4;</code>
     */
    public com.google.protobuf.ByteString
        getHobbiesBytes(int index) {
      return hobbies_.getByteString(index);
    }

    public static final int COURSES_FIELD_NUMBER = 5;
    private java.util.List<com.google.protobuf.ByteString> courses_;
    /**
     * <code>repeated bytes courses = 5;</code>
     */
    public java.util.List<com.google.protobuf.ByteString>
        getCoursesList() {
      return courses_;
    }
    /**
     * <code>repeated bytes courses = 5;</code>
     */
    public int getCoursesCount() {
      return courses_.size();
    }
    /**
     * <code>repeated bytes courses = 5;</code>
     */
    public com.google.protobuf.ByteString getCourses(int index) {
      return courses_.get(index);
    }

    private void initFields() {
      sid_ = 0;
      sname_ = com.google.protobuf.ByteString.EMPTY;
      teacher_ = Teacher.getDefaultInstance();
      hobbies_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      courses_ = java.util.Collections.emptyList();
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt32(1, sid_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBytes(2, sname_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeMessage(3, teacher_);
      }
      for (int i = 0; i < hobbies_.size(); i++) {
        output.writeBytes(4, hobbies_.getByteString(i));
      }
      for (int i = 0; i < courses_.size(); i++) {
        output.writeBytes(5, courses_.get(i));
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, sid_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, sname_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(3, teacher_);
      }
      {
        int dataSize = 0;
        for (int i = 0; i < hobbies_.size(); i++) {
          dataSize += com.google.protobuf.CodedOutputStream
            .computeBytesSizeNoTag(hobbies_.getByteString(i));
        }
        size += dataSize;
        size += 1 * getHobbiesList().size();
      }
      {
        int dataSize = 0;
        for (int i = 0; i < courses_.size(); i++) {
          dataSize += com.google.protobuf.CodedOutputStream
            .computeBytesSizeNoTag(courses_.get(i));
        }
        size += dataSize;
        size += 1 * getCoursesList().size();
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @Override
    protected Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static Student parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Student parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Student parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Student parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Student parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static Student parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static Student parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static Student parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static Student parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static Student parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(Student prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @Override
    protected Builder newBuilderForType(
        BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code Student}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:Student)
        StudentOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return StudentSample.internal_static_Student_descriptor;
      }

      protected FieldAccessorTable
          internalGetFieldAccessorTable() {
        return StudentSample.internal_static_Student_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                Student.class, Builder.class);
      }

      // Construct using StudentSample.Student.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getTeacherFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        sid_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        sname_ = com.google.protobuf.ByteString.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000002);
        if (teacherBuilder_ == null) {
          teacher_ = Teacher.getDefaultInstance();
        } else {
          teacherBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000004);
        hobbies_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000008);
        courses_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000010);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return StudentSample.internal_static_Student_descriptor;
      }

      public Student getDefaultInstanceForType() {
        return Student.getDefaultInstance();
      }

      public Student build() {
        Student result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public Student buildPartial() {
        Student result = new Student(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.sid_ = sid_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.sname_ = sname_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        if (teacherBuilder_ == null) {
          result.teacher_ = teacher_;
        } else {
          result.teacher_ = teacherBuilder_.build();
        }
        if (((bitField0_ & 0x00000008) == 0x00000008)) {
          hobbies_ = hobbies_.getUnmodifiableView();
          bitField0_ = (bitField0_ & ~0x00000008);
        }
        result.hobbies_ = hobbies_;
        if (((bitField0_ & 0x00000010) == 0x00000010)) {
          courses_ = java.util.Collections.unmodifiableList(courses_);
          bitField0_ = (bitField0_ & ~0x00000010);
        }
        result.courses_ = courses_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof Student) {
          return mergeFrom((Student)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(Student other) {
        if (other == Student.getDefaultInstance()) return this;
        if (other.hasSid()) {
          setSid(other.getSid());
        }
        if (other.hasSname()) {
          setSname(other.getSname());
        }
        if (other.hasTeacher()) {
          mergeTeacher(other.getTeacher());
        }
        if (!other.hobbies_.isEmpty()) {
          if (hobbies_.isEmpty()) {
            hobbies_ = other.hobbies_;
            bitField0_ = (bitField0_ & ~0x00000008);
          } else {
            ensureHobbiesIsMutable();
            hobbies_.addAll(other.hobbies_);
          }
          onChanged();
        }
        if (!other.courses_.isEmpty()) {
          if (courses_.isEmpty()) {
            courses_ = other.courses_;
            bitField0_ = (bitField0_ & ~0x00000010);
          } else {
            ensureCoursesIsMutable();
            courses_.addAll(other.courses_);
          }
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        Student parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (Student) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private int sid_ ;
      /**
       * <code>optional int32 sid = 1;</code>
       */
      public boolean hasSid() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>optional int32 sid = 1;</code>
       */
      public int getSid() {
        return sid_;
      }
      /**
       * <code>optional int32 sid = 1;</code>
       */
      public Builder setSid(int value) {
        bitField0_ |= 0x00000001;
        sid_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 sid = 1;</code>
       */
      public Builder clearSid() {
        bitField0_ = (bitField0_ & ~0x00000001);
        sid_ = 0;
        onChanged();
        return this;
      }

      private com.google.protobuf.ByteString sname_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>optional bytes sname = 2;</code>
       */
      public boolean hasSname() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>optional bytes sname = 2;</code>
       */
      public com.google.protobuf.ByteString getSname() {
        return sname_;
      }
      /**
       * <code>optional bytes sname = 2;</code>
       */
      public Builder setSname(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        sname_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional bytes sname = 2;</code>
       */
      public Builder clearSname() {
        bitField0_ = (bitField0_ & ~0x00000002);
        sname_ = getDefaultInstance().getSname();
        onChanged();
        return this;
      }

      private Teacher teacher_ = Teacher.getDefaultInstance();
      private com.google.protobuf.SingleFieldBuilder<
          Teacher, Teacher.Builder, TeacherOrBuilder> teacherBuilder_;
      /**
       * <code>optional .Teacher teacher = 3;</code>
       */
      public boolean hasTeacher() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>optional .Teacher teacher = 3;</code>
       */
      public Teacher getTeacher() {
        if (teacherBuilder_ == null) {
          return teacher_;
        } else {
          return teacherBuilder_.getMessage();
        }
      }
      /**
       * <code>optional .Teacher teacher = 3;</code>
       */
      public Builder setTeacher(Teacher value) {
        if (teacherBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          teacher_ = value;
          onChanged();
        } else {
          teacherBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000004;
        return this;
      }
      /**
       * <code>optional .Teacher teacher = 3;</code>
       */
      public Builder setTeacher(
          Teacher.Builder builderForValue) {
        if (teacherBuilder_ == null) {
          teacher_ = builderForValue.build();
          onChanged();
        } else {
          teacherBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000004;
        return this;
      }
      /**
       * <code>optional .Teacher teacher = 3;</code>
       */
      public Builder mergeTeacher(Teacher value) {
        if (teacherBuilder_ == null) {
          if (((bitField0_ & 0x00000004) == 0x00000004) &&
              teacher_ != Teacher.getDefaultInstance()) {
            teacher_ =
              Teacher.newBuilder(teacher_).mergeFrom(value).buildPartial();
          } else {
            teacher_ = value;
          }
          onChanged();
        } else {
          teacherBuilder_.mergeFrom(value);
        }
        bitField0_ |= 0x00000004;
        return this;
      }
      /**
       * <code>optional .Teacher teacher = 3;</code>
       */
      public Builder clearTeacher() {
        if (teacherBuilder_ == null) {
          teacher_ = Teacher.getDefaultInstance();
          onChanged();
        } else {
          teacherBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000004);
        return this;
      }
      /**
       * <code>optional .Teacher teacher = 3;</code>
       */
      public Teacher.Builder getTeacherBuilder() {
        bitField0_ |= 0x00000004;
        onChanged();
        return getTeacherFieldBuilder().getBuilder();
      }
      /**
       * <code>optional .Teacher teacher = 3;</code>
       */
      public TeacherOrBuilder getTeacherOrBuilder() {
        if (teacherBuilder_ != null) {
          return teacherBuilder_.getMessageOrBuilder();
        } else {
          return teacher_;
        }
      }
      /**
       * <code>optional .Teacher teacher = 3;</code>
       */
      private com.google.protobuf.SingleFieldBuilder<
          Teacher, Teacher.Builder, TeacherOrBuilder>
          getTeacherFieldBuilder() {
        if (teacherBuilder_ == null) {
          teacherBuilder_ = new com.google.protobuf.SingleFieldBuilder<
              Teacher, Teacher.Builder, TeacherOrBuilder>(
                  getTeacher(),
                  getParentForChildren(),
                  isClean());
          teacher_ = null;
        }
        return teacherBuilder_;
      }

      private com.google.protobuf.LazyStringList hobbies_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      private void ensureHobbiesIsMutable() {
        if (!((bitField0_ & 0x00000008) == 0x00000008)) {
          hobbies_ = new com.google.protobuf.LazyStringArrayList(hobbies_);
          bitField0_ |= 0x00000008;
         }
      }
      /**
       * <code>repeated string hobbies = 4;</code>
       */
      public com.google.protobuf.ProtocolStringList
          getHobbiesList() {
        return hobbies_.getUnmodifiableView();
      }
      /**
       * <code>repeated string hobbies = 4;</code>
       */
      public int getHobbiesCount() {
        return hobbies_.size();
      }
      /**
       * <code>repeated string hobbies = 4;</code>
       */
      public String getHobbies(int index) {
        return hobbies_.get(index);
      }
      /**
       * <code>repeated string hobbies = 4;</code>
       */
      public com.google.protobuf.ByteString
          getHobbiesBytes(int index) {
        return hobbies_.getByteString(index);
      }
      /**
       * <code>repeated string hobbies = 4;</code>
       */
      public Builder setHobbies(
          int index, String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureHobbiesIsMutable();
        hobbies_.set(index, value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string hobbies = 4;</code>
       */
      public Builder addHobbies(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureHobbiesIsMutable();
        hobbies_.add(value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string hobbies = 4;</code>
       */
      public Builder addAllHobbies(
          Iterable<String> values) {
        ensureHobbiesIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, hobbies_);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string hobbies = 4;</code>
       */
      public Builder clearHobbies() {
        hobbies_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000008);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string hobbies = 4;</code>
       */
      public Builder addHobbiesBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureHobbiesIsMutable();
        hobbies_.add(value);
        onChanged();
        return this;
      }

      private java.util.List<com.google.protobuf.ByteString> courses_ = java.util.Collections.emptyList();
      private void ensureCoursesIsMutable() {
        if (!((bitField0_ & 0x00000010) == 0x00000010)) {
          courses_ = new java.util.ArrayList<com.google.protobuf.ByteString>(courses_);
          bitField0_ |= 0x00000010;
         }
      }
      /**
       * <code>repeated bytes courses = 5;</code>
       */
      public java.util.List<com.google.protobuf.ByteString>
          getCoursesList() {
        return java.util.Collections.unmodifiableList(courses_);
      }
      /**
       * <code>repeated bytes courses = 5;</code>
       */
      public int getCoursesCount() {
        return courses_.size();
      }
      /**
       * <code>repeated bytes courses = 5;</code>
       */
      public com.google.protobuf.ByteString getCourses(int index) {
        return courses_.get(index);
      }
      /**
       * <code>repeated bytes courses = 5;</code>
       */
      public Builder setCourses(
          int index, com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureCoursesIsMutable();
        courses_.set(index, value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated bytes courses = 5;</code>
       */
      public Builder addCourses(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureCoursesIsMutable();
        courses_.add(value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated bytes courses = 5;</code>
       */
      public Builder addAllCourses(
          Iterable<? extends com.google.protobuf.ByteString> values) {
        ensureCoursesIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, courses_);
        onChanged();
        return this;
      }
      /**
       * <code>repeated bytes courses = 5;</code>
       */
      public Builder clearCourses() {
        courses_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000010);
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:Student)
    }

    static {
      defaultInstance = new Student(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:Student)
  }

  public interface TeacherOrBuilder extends
      // @@protoc_insertion_point(interface_extends:Teacher)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional int32 tid = 1;</code>
     */
    boolean hasTid();
    /**
     * <code>optional int32 tid = 1;</code>
     */
    int getTid();

    /**
     * <code>optional string tname = 2;</code>
     */
    boolean hasTname();
    /**
     * <code>optional string tname = 2;</code>
     */
    String getTname();
    /**
     * <code>optional string tname = 2;</code>
     */
    com.google.protobuf.ByteString
        getTnameBytes();
  }
  /**
   * Protobuf type {@code Teacher}
   */
  public static final class Teacher extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:Teacher)
      TeacherOrBuilder {
    // Use Teacher.newBuilder() to construct.
    private Teacher(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private Teacher(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final Teacher defaultInstance;
    public static Teacher getDefaultInstance() {
      return defaultInstance;
    }

    public Teacher getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private Teacher(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              tid_ = input.readInt32();
              break;
            }
            case 18: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000002;
              tname_ = bs;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return StudentSample.internal_static_Teacher_descriptor;
    }

    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return StudentSample.internal_static_Teacher_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              Teacher.class, Builder.class);
    }

    public static com.google.protobuf.Parser<Teacher> PARSER =
        new com.google.protobuf.AbstractParser<Teacher>() {
      public Teacher parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Teacher(input, extensionRegistry);
      }
    };

    @Override
    public com.google.protobuf.Parser<Teacher> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    public static final int TID_FIELD_NUMBER = 1;
    private int tid_;
    /**
     * <code>optional int32 tid = 1;</code>
     */
    public boolean hasTid() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>optional int32 tid = 1;</code>
     */
    public int getTid() {
      return tid_;
    }

    public static final int TNAME_FIELD_NUMBER = 2;
    private Object tname_;
    /**
     * <code>optional string tname = 2;</code>
     */
    public boolean hasTname() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>optional string tname = 2;</code>
     */
    public String getTname() {
      Object ref = tname_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          tname_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string tname = 2;</code>
     */
    public com.google.protobuf.ByteString
        getTnameBytes() {
      Object ref = tname_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        tname_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private void initFields() {
      tid_ = 0;
      tname_ = "";
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt32(1, tid_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBytes(2, getTnameBytes());
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, tid_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, getTnameBytes());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @Override
    protected Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static Teacher parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Teacher parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Teacher parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Teacher parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Teacher parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static Teacher parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static Teacher parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static Teacher parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static Teacher parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static Teacher parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(Teacher prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @Override
    protected Builder newBuilderForType(
        BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code Teacher}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:Teacher)
        TeacherOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return StudentSample.internal_static_Teacher_descriptor;
      }

      protected FieldAccessorTable
          internalGetFieldAccessorTable() {
        return StudentSample.internal_static_Teacher_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                Teacher.class, Builder.class);
      }

      // Construct using StudentSample.Teacher.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        tid_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        tname_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return StudentSample.internal_static_Teacher_descriptor;
      }

      public Teacher getDefaultInstanceForType() {
        return Teacher.getDefaultInstance();
      }

      public Teacher build() {
        Teacher result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public Teacher buildPartial() {
        Teacher result = new Teacher(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.tid_ = tid_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.tname_ = tname_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof Teacher) {
          return mergeFrom((Teacher)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(Teacher other) {
        if (other == Teacher.getDefaultInstance()) return this;
        if (other.hasTid()) {
          setTid(other.getTid());
        }
        if (other.hasTname()) {
          bitField0_ |= 0x00000002;
          tname_ = other.tname_;
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        Teacher parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (Teacher) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private int tid_ ;
      /**
       * <code>optional int32 tid = 1;</code>
       */
      public boolean hasTid() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>optional int32 tid = 1;</code>
       */
      public int getTid() {
        return tid_;
      }
      /**
       * <code>optional int32 tid = 1;</code>
       */
      public Builder setTid(int value) {
        bitField0_ |= 0x00000001;
        tid_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 tid = 1;</code>
       */
      public Builder clearTid() {
        bitField0_ = (bitField0_ & ~0x00000001);
        tid_ = 0;
        onChanged();
        return this;
      }

      private Object tname_ = "";
      /**
       * <code>optional string tname = 2;</code>
       */
      public boolean hasTname() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>optional string tname = 2;</code>
       */
      public String getTname() {
        Object ref = tname_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            tname_ = s;
          }
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>optional string tname = 2;</code>
       */
      public com.google.protobuf.ByteString
          getTnameBytes() {
        Object ref = tname_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          tname_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string tname = 2;</code>
       */
      public Builder setTname(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        tname_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string tname = 2;</code>
       */
      public Builder clearTname() {
        bitField0_ = (bitField0_ & ~0x00000002);
        tname_ = getDefaultInstance().getTname();
        onChanged();
        return this;
      }
      /**
       * <code>optional string tname = 2;</code>
       */
      public Builder setTnameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        tname_ = value;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:Teacher)
    }

    static {
      defaultInstance = new Teacher(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:Teacher)
  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Student_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_Student_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Teacher_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_Teacher_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    String[] descriptorData = {
      "\n\022StudentSampe.proto\"b\n\007Student\022\013\n\003sid\030\001" +
      " \001(\005\022\r\n\005sname\030\002 \001(\014\022\031\n\007teacher\030\003 \001(\0132\010.T" +
      "eacher\022\017\n\007hobbies\030\004 \003(\t\022\017\n\007courses\030\005 \003(\014" +
      "\"%\n\007Teacher\022\013\n\003tid\030\001 \001(\005\022\r\n\005tname\030\002 \001(\tB" +
      "\017B\rStudentSample"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_Student_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_Student_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_Student_descriptor,
        new String[] { "Sid", "Sname", "Teacher", "Hobbies", "Courses", });
    internal_static_Teacher_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_Teacher_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_Teacher_descriptor,
        new String[] { "Tid", "Tname", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
